aws_profile: krugsls
app: krug-sls-share
region: ap-northeast-2
useAWSSDKV3: true

env:
  stage: prod
  service: krug-sls-share
test_targets:
  - uri: upload/put.js
    eventType: http
    description: template get
    method: get
    parms:
      code: sls-0225
      bucket: krug-sls-share.prod.ap-northeast-2-filebucket
      key: krugsls/2025-02-25/AWS_KRUG서버리스소모임_발표자료_2025_02_25.zip
      description: krug
    expect:
      checkType: check_200

  - uri: download/get.js
    eventType: http
    description: template get
    method: get
    parms:
      code: sls-02-25

    expect:
      checkType: check_200
